### ISSUE TITLE
Multiple consumer keys

### ISSUE THREAD

**Issue by EArbeitman** [davidmreed/septaTrains#8]
Hi,

This project has been super helpful so far. Had a question about deploying to multiple orgs. I don't believe the consumer keys will persist when a connected app is deployed to sandboxes. Reason I mention this is because I'm trying to deploy to different sandboxes - but the consumer key will change between orgs. Any ideas on how to work around this?

**Comment by davidmreed** [comment]
I would not use this exact CI setup with sandboxes, necessarily - there's no provision for removing metadata items, for one thing. 

That said... if you have say one branch per sandbox (`master`, `featureA`, `featureB`, etc.), one approach would be to define the a consumer key variable for each branch+sandbox, and use Bash variable interpolation to get the "right" variable on each build, by doing something like

KEYVAR="CONSUMERKEY_$CIRCLE_BRANCH"

and then authorizing with `--clientid ${!KEYVAR}`

Your project environment variables would include settings like `CONSUMERKEY_master` and `CONSUMERKEY_featureA`.

**Comment by EArbeitman** [comment]
This worked like a charm. only issue I see is that those env variables will only persist for the command that they are executed in. Perhaps I can create job level variables like this:

`     environment:
         KEYVAR: "CONSUMERKEY_" + $CIRCLE_BRANCH"
        #USERNAME: "USERNAME_" + $CIRCLE_BRANCH"
`

**Comment by davidmreed** [comment]
Yeah, that looks pretty workable to me. Link me a repo if you end up sharing this!
